# version: "3.9"
services:
  mysql:
    image: 'mariadb:11.2.6'
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal-website
    ports:
      - 3306:3306

  # mailer:
  #   image: schickling/mailcatcher
  #   ports: 
  #     - 1080:1080
  #     - 1025:1025
